### ISSUE TITLE
Can't add the + in the infographic place, i.e 50,000+

### ISSUE THREAD

**Issue by fady-json** [Developers-Foundation/developersfoundation#64]
`<div id="tf-clients" class="text-center">
        <div class="overlay">
            <div class="container">
                <div class="counter-area">
                    <div class="col-md-4 col-sm-6 col-xs-6">
                        <div class="single-counter">
                            <span class="fa fa-users"></span>
                            <div class="counter-count">
                                <span class="counter">15</span>
                                <p>Happy Clients</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-6">
                        <div class="single-counter">
                            <span class="fa fa-code"></span>
                            <div class="counter-count">
                                <span class="counter">35,000</span>
                                <p>Lines of code</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-6">
                        <div class="single-counter">
                            <span class="fa fa-users"></span>
                            <div class="counter-count">
                                <span class="counter">50,000</span>
                                <p>People affected</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>`

**Comment by nobodyrandom** [comment]
lol whut is this
