### ISSUE TITLE
Microsoft subdomain

### ISSUE THREAD

**Issue by fady-json** [Developers-Foundation/developersfoundation#66]
http://microsoft.developersfoundation.ca/ directs to https://developersfoundation.ca/microsoft.php, put throws an error

**Comment by nobodyrandom** [comment]
@Fadyazmy it is due to developersfoundation.ca pointing to your repo. Can you put in a redirect of developersfoundation.ca/microsoft.php to devfoundation.herokuapp.com/microsoft.php

**Comment by fady-json** [comment]
@nobodyrandom  this is on namecheap yes?

**Comment by nobodyrandom** [comment]
no

**Comment by fady-json** [comment]
=.= helpful reply

**Comment by nobodyrandom** [comment]
put this php file into your repo inside public_html

microsoft.php
```
<?php
header("Location: https://devfoundation.herokuapp.com/microsoft.php");
die();
?>
```

**Comment by fady-json** [comment]
done (Y)

**Comment by fady-json** [comment]
issue still exists, but I'm not sure why haha

**Comment by nobodyrandom** [comment]
did you clear cache?
+ spell it correctly?

**Comment by fady-json** [comment]
I did, you can check?

**Comment by nobodyrandom** [comment]
Try repush

**Comment by nobodyrandom** [comment]
as in heroku redeploy

**Comment by fady-json** [comment]
heroku/ms works, not devfound/ms

**Comment by nobodyrandom** [comment]
http://devfound.herokuapp.com/microsoft.php 

???

**Comment by nobodyrandom** [comment]
https://shielded-shelf-89150.herokuapp.com/microsoft.php

not working either

**Comment by nobodyrandom** [comment]
https://dashboard.heroku.com/apps/shielded-shelf-89150/activity/builds/20ea7ae9-f6db-4f38-ad59-a2fdcd42ce63

Check your build log, it failed building....

**Comment by nobodyrandom** [comment]
Yeah I found the error, you used `git add .`

@Fadyazmy

**Comment by nobodyrandom** [comment]
Run these commands:

```
git rm --cached .idea
git rm --cached composer.phar
git push
```

Should fix most of the problems, remember: Never use `git add .`

**Comment by fady-json** [comment]
fudge, really =.= argh. Heroku log was fine =.=

**Comment by fady-json** [comment]
did, still no good - this works: https://devfoundation.herokuapp.com/microsoft

**Comment by nobodyrandom** [comment]
Yes that works because I wrote it lol, but https://shielded-shelf-89150.herokuapp.com/microsoft.php doesnt work

**Comment by nobodyrandom** [comment]
builds are still failing, @Fadyazmy did you run `git rm --cached composer.phar`?

try commit after running that, then push

I do not see the updates on the repo.... This repo: https://github.com/Developers-Foundation/devfound

**Comment by fady-json** [comment]
didn't work properly initially - now done

**Comment by nobodyrandom** [comment]
Yeah, there are still too many files that shouldnt be there, Run these commands

```
git rm --cached vendor
git rm --cached .idea
git commit -m "abc"
git push
```

**Comment by nobodyrandom** [comment]
We need to implement a policy to force all client websites to use blank_bootstrap soon =,=

So this does not happen in the future

**Comment by fady-json** [comment]
Agreed - but I think this an edge situation since most products won't have redirects

**Comment by nobodyrandom** [comment]
No this is not the only issue, just having all applications having the same folder hierarchy is a good idea. And it centralized all .htaccess composer and related stuff so you guys don't need to know what is going on to use it

**Comment by nobodyrandom** [comment]
There's also the app json, gitignore and also the mailer and everything else.

**Comment by fady-json** [comment]
I understand - https://devfoundation.herokuapp.ca/microsoft.php now doesn't work =]

**Comment by nobodyrandom** [comment]
It's not supposed to be .ca, it should be .com

**Comment by fady-json** [comment]
that is the redirect

**Comment by nobodyrandom** [comment]
Try again, I've put in a patch
